# Generated by Django 2.0.6 on 2019-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallopsnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
