# Generated by Django 2.0.6 on 2019-04-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallopsnews', '0004_remove_article_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
