# Generated by Django 2.0.6 on 2019-04-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallopsnews', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
